package org.shirakawatyu.yamibo.novel.util.theme

val DARK_MODE_CSS_RULES_OLED = listOf(
    "/* === CSS 变量覆盖 (OLED 极致黑版) === */",
    "body {",
    "--dz-BG-body: oklch(0% 0 0) !important;",
    "--dz-BG-0: oklch(12% 0 0) !important;",
    "--dz-BG-5: oklch(16% 0 0) !important;",
    "--dz-BG-6: oklch(25% 0 0) !important;",
    "--dz-FC-fff: oklch(85% 0 0) !important;",
    "--dz-FC-333: oklch(75% 0 0) !important;",
    "--dz-FC-666: oklch(65% 0 0) !important;",
    "--dz-FC-999: oklch(55% 0 0) !important;",
    "--dz-FC-ccc: oklch(60% 0 0) !important;",
    "--dz-FC-aaa: oklch(50% 0 0) !important;",
    "--dz-BOR-ed: oklch(20% 0 0) !important;",
    "--dz-FC-color: oklch(75% 0 0) !important;",
    "}",
    "html, body { background: oklch(0% 0 0) !important; }",
    ".wp, #wp, .content, .main, .wrapper { background: oklch(0% 0 0) !important; }",
    ".header { background: oklch(8% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".header, .header h2, .header h2 a, .header a { color: oklch(85% 0 0) !important; }",
    ".header_toplogo { background: oklch(8% 0 0) !important; }",
    ".header_toplogo p { color: oklch(85% 0 0) !important; }",
    "#nav-more-menu { background: oklch(12% 0 0) !important; }",
    ".nav-more-item { color: oklch(75% 0 0) !important; }",
    ".nav-more-item-text { color: oklch(75% 0 0) !important; }",
    ".nav-more-item svg { fill: oklch(75% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".sq_nav, .thread_nav, .sq_nav ul, .thread_nav ul { background: oklch(8% 0 0) !important; }",
    ".sq_nav a, .thread_nav a { color: oklch(65% 0 0) !important; }",
    ".sq_nav .a a, .thread_nav .a a, .sq_nav a.active, .thread_nav a.active { color: oklch(95% 0 0) !important; background: oklch(20% 0 0) !important; }",
    ".z, .vertical_tab { background: oklch(8% 0 0) !important; }",
    ".z a, .vertical_tab a { color: oklch(65% 0 0) !important; }",
    ".z .a, .vertical_tab .a, .z a.active, .vertical_tab a.active { color: oklch(95% 0 0) !important; background: oklch(20% 0 0) !important; }",
    ".plc .z, .plc .flex-2, .plc .xg1, .plc .xw1 { background: oklch(12% 0 0) !important; }",
    ".forumdisplay-top { background: oklch(12% 0 0) !important; }",
    ".forumdisplay-top h2, .forumdisplay-top h2 a { color: oklch(85% 0 0) !important; }",
    ".forumdisplay-top p, .forumdisplay-top p span { color: oklch(65% 0 0) !important; }",
    ".dhnav_box, #dhnav, #dhnav_li { background: oklch(8% 0 0) !important; }",
    ".dhnav_box a, #dhnav a { color: oklch(65% 0 0) !important; }",
    ".dhnav_box .mon a, #dhnav .mon a { color: oklch(95% 0 0) !important; }",
    ".tabs a.mon, .dhnv a.mon, #dhnav_li li.mon { border-bottom-color: oklch(35% 0 0) !important; }",
    ".dhnavs_box, #dhnavs { background: oklch(8% 0 0) !important; }",
    "#dhnavs .swiper-slide a { color: oklch(65% 0 0) !important; }",
    "#dhnavs .swiper-slide.mon a { color: oklch(95% 0 0) !important; }",
    ".forumlist, .forumlist > div, .forumlist .mlist1 { background: oklch(0% 0 0) !important; }",
    ".forumlist .subforumshow { background: oklch(8% 0 0) !important; }",
    ".subforumshow { background: oklch(8% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".subforumshow h2 a { color: oklch(75% 0 0) !important; }",
    ".subforumshow i { color: oklch(55% 0 0) !important; }",
    ".subforumshow { color: oklch(65% 0 0) !important; }",
    ".murl .mtit, .sub-forum .murl .mtit { color: oklch(75% 0 0) !important; }",
    ".mlist1, .mlist1 ul, .mlist1 li, .mlist1 li a, .mlist1 li span { background: oklch(12% 0 0) !important; }",
    ".mlist1 li { border-color: oklch(18% 0 0) !important; }",
    ".mlist1 .mtit { color: oklch(85% 0 0) !important; }",
    ".mlist1 .mtxt { color: oklch(60% 0 0) !important; }",
    ".mlist1 .mnum { color: oklch(50% 0 0) !important; }",
    ".bm, .bm_c, .bm_h { background: oklch(12% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".bm_h, .bm_h h2, .bm_h a { color: oklch(75% 0 0) !important; }",
    ".tl_bm, .tl_bm ul, .tl_bm li, .tl_bm li a { background: oklch(12% 0 0) !important; }",
    ".threadlist { background: oklch(8% 0 0) !important; }",
    ".threadlist li, .threadlist li a { background: oklch(12% 0 0) !important; }",
    ".tl_bm li, .threadlist li { border-color: oklch(18% 0 0) !important; }",
    ".tl_bm a, .threadlist a { color: oklch(75% 0 0) !important; }",
    ".view_tit, .view_tit h1, .view_tit a, .view_tit em { background: oklch(12% 0 0) !important; color: oklch(85% 0 0) !important; }",
    ".pls, .pls div, .pls a { background: oklch(8% 0 0) !important; }",
    ".pls, .pls a, .pls em, .pls span { color: oklch(75% 0 0) !important; }",
    ".plc, .plm, .plc div, .plm div { background: oklch(12% 0 0) !important; }",
    ".authi, .authi em, .authi a, .authi span { color: oklch(65% 0 0) !important; }",
    ".message, .postmessage, .t_f, .t_msgfont, .message div, .t_f div { color: oklch(75% 0 0) !important; }",
    ".message a, .postmessage a, .t_f a, .t_msgfont a { color: oklch(75% 0.12 245) !important; }",
    ".pgs, .pgs a, .pg, .pg a { background: oklch(16% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(25% 0 0) !important; }",
    ".page { background: oklch(0% 0 0) !important; }",
    ".page a { background: oklch(16% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(25% 0 0) !important; }",
    ".pgs .pg strong, .pg strong, .page strong { background: oklch(25% 0 0) !important; color: oklch(95% 0 0) !important; }",
    ".xi1 { color: oklch(85% 0 0) !important; }",
    ".xi2 { color: oklch(75% 0 0) !important; }",
    ".xg1, .xg1 a { color: oklch(65% 0 0) !important; }",
    ".xg2, .xg2 a { color: oklch(60% 0 0) !important; }",
    ".num, .views, .replies { color: oklch(55% 0 0) !important; }",
    ".ts, .time { color: oklch(50% 0 0) !important; }",
    ".pipe { color: oklch(20% 0 0) !important; }",
    ".lock, .closed, .icn, .attach, .tattl { color: oklch(55% 0 0) !important; }",
    ".dialog, .ui-dialog, .bootstrap-dialog, .pop, .p_pop, .p_pop div { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".dialog a, .ui-dialog a, .p_pop a { color: oklch(75% 0 0) !important; }",
    ".foot_reply, .f_c, .foot, #f_c { background: oklch(12% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".foot_reply a, .f_c a, .foot a { color: oklch(75% 0 0) !important; }",
    ".viewt-reply, .viewt-reply a { background: oklch(20% 0 0) !important; color: oklch(95% 0 0) !important; }",
    ".fico-launch, .dm-star, .fico-reply, .fico-favorite, .fico-share, .fico { color: oklch(75% 0 0) !important; }",
    ".my, .my a, .my i, .my span { color: oklch(75% 0 0) !important; }",
    ".mz, .mz a, .mz i, .mz span { color: oklch(65% 0 0) !important; }",
    ".myinfo_list_ico, .myinfo_list_ico ul { background: oklch(12% 0 0) !important; }",
    ".myinfo_list_ico li  { background: oklch(12% 0 0) !important; }",
    ".myinfo_list_ico li a { background: oklch(8% 0 0) !important; }",
    ".myinfo_list_ico li { border-color: oklch(18% 0 0) !important; }",
    ".myinfo_list_ico li a { color: oklch(75% 0 0) !important; }",
    ".myinfo_list_ico li i { color: oklch(90% 0 0) !important; }",
    ".myinfo, .myinfo_menu, .profile_section, .profile_section a { background: oklch(12% 0 0) !important; }",
    ".myinfo a, .myinfo_menu a { color: oklch(75% 0 0) !important; }",
    ".myinfo_list, .myinfo_list li { border-color: oklch(18% 0 0) !important; }",
    ".myinfo_list li span { color: oklch(65% 0 0) !important; }",
    ".myinfo_list b { color: oklch(75% 0 0) !important; }",
    ".mtag, .profile_tag { color: oklch(55% 0 0) !important; }",
    "table, tbody, td, th, .t_table, .t_table td, .t_table th { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(18% 0 0) !important; }",
    ".footer, #footer { background: oklch(8% 0 0) !important; color: oklch(55% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".footer a, #footer a { color: oklch(55% 0 0) !important; }",
    ".footer-nv, .footer-nv a, .footer-copy, .footer-copy a { background: oklch(8% 0 0) !important; color: oklch(55% 0 0) !important; }",
    ".footer .mon { color: oklch(55% 0 0) !important; }",
    "input, select, textarea { background: oklch(18% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(25% 0 0) !important; }",
    "blockquote, .quote, .blockcode { background: oklch(16% 0 0) !important; border-color: oklch(25% 0 0) !important; color: oklch(65% 0 0) !important; }",
    "hr, .line, .partition { border-color: oklch(20% 0 0) !important; }",
    ".notice, .tip, .alert, .warning, .tips { background: oklch(16% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(25% 0 0) !important; }",
    ".avatar img, .avatar, .my_avatar img { border-color: oklch(20% 0 0) !important; }",
    ".btn, .button, button, .pn, .pnc, .mbtn { background: oklch(20% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(30% 0 0) !important; }",
    "#postform, #fastpostform, .area textarea { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(25% 0 0) !important; }",
    ".psth { background: oklch(8% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".psth .icon_ring { color: oklch(55% 0 0) !important; }",
    ".showcollapse_box { background: oklch(12% 0 0) !important; border-color: oklch(18% 0 0) !important; }",
    ".showcollapse_title { background: oklch(16% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".showcollapse_content { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".showcollapse_content a { color: oklch(75% 0.12 245) !important; }",
    ".showcollapse_gather { color: oklch(55% 0 0) !important; }",
    ".message *[style*=\"background\" i] { background-color: transparent !important; }",
    "font[color] { color: oklch(75% 0 0) !important; }",
    "font[color=\"#ff0000\" i], font[color=\"red\" i] { color: oklch(60% 0.17 25) !important; }",
    ".threadlist_foot { background: oklch(12% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".threadlist_foot a, .threadlist_foot i, .threadlist_foot em { color: oklch(55% 0 0) !important; }",
    ".threadlist_foot li { border: 1px solid oklch(30% 0 0) !important; outline: none !important; box-shadow: none !important; }",
    ".threadlist_foot li.mr { border: none !important; }",
    ".threadlist_foot .dm-heart, .threadlist_foot .dm-chat-s, .dm-heart, .dm-chat-s, .dm-eye-fill, .dm-chat-s-fill { color: oklch(55% 0 0) !important; }",
    ".threadlist_top, .threadlist_top a, .threadlist_top .mimg, .threadlist_top .muser { background: oklch(12% 0 0) !important; }",
    ".threadlist_top .mmc { color: oklch(75% 0 0) !important; }",
    ".threadlist_top .mtime { color: oklch(50% 0 0) !important; }",
    ".threadlist_tit, .threadlist_tit em, .threadlist_tit a { background: oklch(12% 0 0) !important; color: oklch(85% 0 0) !important; }",
    ".threadlist_mes, .threadlist_mes a { background: oklch(12% 0 0) !important; color: oklch(60% 0 0) !important; }",
    ".discuz_x { background: oklch(12% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".txtlist, .txtlist .mtit { background: oklch(8% 0 0) !important; color: oklch(75% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".txtlist .ytxt, .txtlist a { color: oklch(65% 0 0) !important; }",
    ".mtime, .mtime span, .mtime em, .mtime i { color: oklch(55% 0 0) !important; }",
    ".y, .y span, .y em, .y i { color: oklch(55% 0 0) !important; }",
    ".pstatus, .pstatus font { color: oklch(55% 0 0) !important; }",
    ".float-menu-item { background: oklch(20% 0 0 / 0.85) !important; color: oklch(75% 0 0) !important; }",
    ".float-menu-item svg { fill: oklch(75% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".scrolltop { background: oklch(20% 0 0) !important; }",
    "#mask { background: oklch(0% 0 0 / 0.8) !important; }",
    "strong, b, .strong { color: oklch(85% 0 0) !important; }",
    "sup, sub { color: oklch(65% 0 0) !important; }",
    "em { color: oklch(75% 0 0) !important; }",
    ".display, .pi { background: oklch(12% 0 0) !important; }",
    ".plc .avatar { z-index: 10 !important; background: transparent !important; }",
    ".plc .display, .plc .pi { background: transparent !important; }",
    ".hui-header { background: oklch(8% 0 0) !important; }",
    ".hui-header h1 { color: oklch(85% 0 0) !important; }",
    ".hui-slide-menu { background: oklch(12% 0 0) !important; }",
    ".hui-slide-menu li { color: oklch(75% 0 0) !important; }",
    ".hui-wrap { background: oklch(0% 0 0) !important; }",
    ".hui-common-title-line { border-color: oklch(20% 0 0) !important; }",
    ".hui-common-title-txt { color: oklch(75% 0 0) !important; }",
    ".hui-content { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".hui-media-list li { background: oklch(12% 0 0) !important; border-color: oklch(20% 0 0) !important; }",
    ".hui-media-content { background: oklch(12% 0 0) !important; }",
    ".hui-media-content p { color: oklch(75% 0 0) !important; }",
    ".hui-media-content a { color: oklch(75% 0.12 245) !important; }",
    ".hui-list { background: oklch(12% 0 0) !important; }",
    ".hui-list-text { color: oklch(75% 0 0) !important; }",
    ".hui-center-title h2 { color: oklch(85% 0 0) !important; }",
    ".hui-button { background: oklch(20% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".hui-primary { background: oklch(55% 0.16 45) !important; color: oklch(95% 0 0) !important; }",
    ".fl-table { background: oklch(12% 0 0) !important; }",
    ".fl-table th { background: oklch(16% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".fl-table td { background: oklch(12% 0 0) !important; color: oklch(75% 0 0) !important; }",
    ".day { color: oklch(75% 0 0) !important; }",
    ".day.today { background: oklch(55% 0.16 45) !important; color: oklch(95% 0 0) !important; }",
    ".lunar { color: oklch(55% 0 0) !important; }",
    ".signbtn .btna { background: oklch(55% 0.16 45) !important; color: oklch(95% 0 0) !important; }",
    ".authi .mtit, .authi .mtime { color: oklch(55% 0 0) !important; }",
    ".pswp__button, .pswp__button:hover, .pswp__button:active { background: transparent !important; border-color: transparent !important; box-shadow: none !important; }"
)
