package org.shirakawatyu.yamibo.novel.util.theme

val DARK_MODE_CSS_RULES_CLASSIC = listOf(
    "/* === CSS 变量覆盖 === */",
    "body {",
    "--dz-BG-body: #121212 !important;",
    "--dz-BG-0: #1e1e1e !important;",
    "--dz-BG-5: #252525 !important;",
    "--dz-BG-6: #444444 !important;",
    "--dz-FC-fff: #dddddd !important;",
    "--dz-FC-333: #bbbbbb !important;",
    "--dz-FC-666: #aaaaaa !important;",
    "--dz-FC-999: #888888 !important;",
    "--dz-FC-ccc: #999999 !important;",
    "--dz-FC-aaa: #777777 !important;",
    "--dz-BOR-ed: #333333 !important;",
    "--dz-FC-color: #bbbbbb !important;",
    "}",
    "/* === 页面根背景 === */",
    "html, body { background: #121212 !important; }",
    "/* === 主容器 === */",
    ".wp, #wp, .content, .main, .wrapper { background: #121212 !important; }",
    "/* === 顶部导航栏 === */",
    ".header { background: #1a1a1a !important; border-color: #333 !important; }",
    ".header, .header h2, .header h2 a, .header a { color: #dddddd !important; }",
    ".header_toplogo { background: #1a1a1a !important; }",
    ".header_toplogo p { color: #dddddd !important; }",
    "/* === 顶部更多菜单 (只看楼主/倒序/返回首页/电脑版) === */",
    "#nav-more-menu { background: #1e1e1e !important; }",
    ".nav-more-item { color: #bbbbbb !important; }",
    ".nav-more-item-text { color: #bbbbbb !important; }",
    ".nav-more-item svg { fill: #bbbbbb !important; color: #bbbbbb !important; }",
    "/* === 导航标签 (只看他/倒序/阅读模式等) === */",
    ".sq_nav, .thread_nav, .sq_nav ul, .thread_nav ul { background: #1a1a1a !important; }",
    ".sq_nav a, .thread_nav a { color: #aaaaaa !important; }",
    ".sq_nav .a a, .thread_nav .a a, .sq_nav a.active, .thread_nav a.active { color: #fff !important; background: #333 !important; }",
    "/* === 版块导航 .z (分区/标签) === */",
    ".z, .vertical_tab { background: #1a1a1a !important; }",
    ".z a, .vertical_tab a { color: #aaaaaa !important; }",
    ".z .a, .vertical_tab .a, .z a.active, .vertical_tab a.active { color: #ffffff !important; background: #333 !important; }",
    ".plc .z, .plc .flex-2, .plc .xg1, .plc .xw1 { background: #1e1e1e !important; }",
    "/* === 版块顶部信息栏 === */",
    ".forumdisplay-top { background: #1e1e1e !important; }",
    ".forumdisplay-top h2, .forumdisplay-top h2 a { color: #dddddd !important; }",
    ".forumdisplay-top p, .forumdisplay-top p span { color: #aaaaaa !important; }",
    "/* === 排序标签导航 (全部/最新/热门/新帖/精华) === */",
    ".dhnav_box, #dhnav, #dhnav_li { background: #1a1a1a !important; }",
    ".dhnav_box a, #dhnav a { color: #aaaaaa !important; }",
    ".dhnav_box .mon a, #dhnav .mon a { color: #ffffff !important; }",
    ".tabs a.mon, .dhnv a.mon, #dhnav_li li.mon { border-bottom-color: #666666 !important; }",
    ".dhnavs_box, #dhnavs { background: #1a1a1a !important; }",
    "#dhnavs .swiper-slide a { color: #aaaaaa !important; }",
    "#dhnavs .swiper-slide.mon a { color: #ffffff !important; }",
    "/* === 论坛列表容器 === */",
    ".forumlist, .forumlist > div, .forumlist .mlist1 { background: #121212 !important; }",
    ".forumlist .subforumshow { background: #1a1a1a !important; }",
    "/* === 分区标题栏 === */",
    ".subforumshow { background: #1a1a1a !important; border-color: #333 !important; }",
    ".subforumshow h2 a { color: #bbbbbb !important; }",
    ".subforumshow i { color: #888888 !important; }",
    ".subforumshow { color: #aaaaaa !important; }",
    ".murl .mtit, .sub-forum .murl .mtit { color: #bbbbbb !important; }",
    "/* === 版块列表项 (含内部 a 标签背景覆盖) === */",
    ".mlist1, .mlist1 ul, .mlist1 li, .mlist1 li a, .mlist1 li span { background: #1e1e1e !important; }",
    ".mlist1 li { border-color: #2a2a2a !important; }",
    ".mlist1 .mtit { color: #dddddd !important; }",
    ".mlist1 .mtxt { color: #999999 !important; }",
    ".mlist1 .mnum { color: #777777 !important; }",
    "/* === 通用板块容器 (Discuz 模板) === */",
    ".bm, .bm_c, .bm_h { background: #1e1e1e !important; border-color: #333 !important; }",
    ".bm_h, .bm_h h2, .bm_h a { color: #bbbbbb !important; }",
    "/* === 帖子列表 === */",
    ".tl_bm, .tl_bm ul, .tl_bm li, .tl_bm li a { background: #1e1e1e !important; }",
    ".threadlist { background: #1a1a1a !important; }",
    ".threadlist li, .threadlist li a { background: #1e1e1e !important; }",
    ".tl_bm li, .threadlist li { border-color: #2a2a2a !important; }",
    ".tl_bm a, .threadlist a { color: #bbbbbb !important; }",
    "/* === 帖子详情 - 标题 === */",
    ".view_tit, .view_tit h1, .view_tit a, .view_tit em { background: #1e1e1e !important; color: #dddddd !important; }",
    "/* === 帖子详情 - 楼主信息栏 === */",
    ".pls, .pls div, .pls a { background: #1a1a1a !important; }",
    ".pls, .pls a, .pls em, .pls span { color: #bbbbbb !important; }",
    "/* === 帖子详情 - 帖子内容容器 === */",
    ".plc, .plm, .plc div, .plm div { background: #1e1e1e !important; }",
    "/* === 帖子详情 - 作者行 === */",
    ".authi, .authi em, .authi a, .authi span { color: #aaaaaa !important; }",
    "/* === 帖子详情 - 文本颜色 === */",
    ".message, .postmessage, .t_f, .t_msgfont, .message div, .t_f div { color: #bbbbbb !important; }",
    "/* === 帖子中的链接 === */",
    ".message a, .postmessage a, .t_f a, .t_msgfont a { color: #7eb8da !important; }",
    "/* === 分页导航 === */",
    ".pgs, .pgs a, .pg, .pg a { background: #252525 !important; color: #bbbbbb !important; border-color: #444 !important; }",
    ".page { background: #121212 !important; }",
    ".page a { background: #252525 !important; color: #bbbbbb !important; border-color: #444 !important; }",
    ".pgs .pg strong, .pg strong, .page strong { background: #444 !important; color: #fff !important; }",
    "/* === Discuz 颜色工具类 === */",
    ".xi1 { color: #dddddd !important; }",
    ".xi2 { color: #bbbbbb !important; }",
    ".xg1, .xg1 a { color: #aaaaaa !important; }",
    ".xg2, .xg2 a { color: #999999 !important; }",
    "/* === 帖子元信息 === */",
    ".num, .views, .replies { color: #888888 !important; }",
    ".ts, .time { color: #777777 !important; }",
    ".pipe { color: #444 !important; }",
    "/* === 锁/图章/图标 === */",
    ".lock, .closed, .icn, .attach, .tattl { color: #888888 !important; }",
    "/* === 弹窗/对话框 === */",
    ".dialog, .ui-dialog, .bootstrap-dialog, .pop, .p_pop, .p_pop div { background: #1e1e1e !important; color: #bbbbbb !important; }",
    ".dialog a, .ui-dialog a, .p_pop a { color: #bbbbbb !important; }",
    "/* === 底部回复栏 === */",
    ".foot_reply, .f_c, .foot, #f_c { background: #1e1e1e !important; border-color: #333 !important; }",
    ".foot_reply a, .f_c a, .foot a { color: #bbbbbb !important; }",
    ".viewt-reply, .viewt-reply a { background: #333 !important; color: #fff !important; }",
    ".fico-launch, .dm-star, .fico-reply, .fico-favorite, .fico-share, .fico { color: #bbbbbb !important; }",
    "/* === 个人中心导航 === */",
    ".my, .my a, .my i, .my span { color: #bbbbbb !important; }",
    ".mz, .mz a, .mz i, .mz span { color: #aaaaaa !important; }",
    "/* === 个人中心功能列表 (含内部 a 标签背景覆盖) === */",
    ".myinfo_list_ico, .myinfo_list_ico ul { background: #1e1e1e !important; }",
    ".myinfo_list_ico li  { background: #1e1e1e !important; }",
    ".myinfo_list_ico li a { background: #1a1a1a !important; }",
    ".myinfo_list_ico li { border-color: #2a2a2a !important; }",
    ".myinfo_list_ico li a { color: #bbbbbb !important; }",
    ".myinfo_list_ico li i { color: #EEEEEE !important; }",
    "/* === 个人中心其他区块 === */",
    ".myinfo, .myinfo_menu, .profile_section, .profile_section a { background: #1e1e1e !important; }",
    ".myinfo a, .myinfo_menu a { color: #bbbbbb !important; }",
    ".myinfo_list, .myinfo_list li { border-color: #2a2a2a !important; }",
    ".myinfo_list li span { color: #aaaaaa !important; }",
    ".myinfo_list b { color: #bbbbbb !important; }",
    ".mtag, .profile_tag { color: #888888 !important; }",
    "/* === 表格 === */",
    "table, tbody, td, th, .t_table, .t_table td, .t_table th { background: #1e1e1e !important; color: #bbbbbb !important; border-color: #2a2a2a !important; }",
    "/* === 页脚 === */",
    ".footer, #footer { background: #1a1a1a !important; color: #888888 !important; border-color: #333 !important; }",
    ".footer a, #footer a { color: #888888 !important; }",
    ".footer-nv, .footer-nv a, .footer-copy, .footer-copy a { background: #1a1a1a !important; color: #888888 !important; }",
    ".footer .mon { color: #888888 !important; }",
    "/* === input/select 控件 === */",
    "input, select, textarea { background: #2a2a2a !important; color: #bbbbbb !important; border-color: #444 !important; }",
    "/* === 引用/代码块 === */",
    "blockquote, .quote, .blockcode { background: #252525 !important; border-color: #444 !important; color: #aaaaaa !important; }",
    "/* === 分割线 === */",
    "hr, .line, .partition { border-color: #333 !important; }",
    "/* === 通知/提示条 === */",
    ".notice, .tip, .alert, .warning, .tips { background: #252525 !important; color: #bbbbbb !important; border-color: #444 !important; }",
    "/* === 头像边框适配 === */",
    ".avatar img, .avatar, .my_avatar img { border-color: #333 !important; }",
    "/* === 按钮通用 === */",
    ".btn, .button, button, .pn, .pnc, .mbtn { background: #333 !important; color: #bbbbbb !important; border-color: #555 !important; }",
    "/* === 快速回复框 === */",
    "#postform, #fastpostform, .area textarea { background: #1e1e1e !important; color: #bbbbbb !important; border-color: #444 !important; }",
    "/* === 点评/评分标题 === */",
    ".psth { background: #1a1a1a !important; color: #bbbbbb !important; border-color: #333 !important; }",
    ".psth .icon_ring { color: #888888 !important; }",
    "/* === 目录/章节折叠列表 === */",
    ".showcollapse_box { background: #1e1e1e !important; border-color: #2a2a2a !important; }",
    ".showcollapse_title { background: #252525 !important; color: #bbbbbb !important; border-color: #333 !important; }",
    ".showcollapse_content { background: #1e1e1e !important; color: #bbbbbb !important; }",
    ".showcollapse_content a { color: #7eb8da !important; }",
    ".showcollapse_gather { color: #888888 !important; }",
    "/* === 帖子内联高亮 (覆盖 inline style) 强制清除发帖人自带底色 === */",
    ".message *[style*=\"background\" i] { background-color: transparent !important; }",
    "font[color] { color: #bbbbbb !important; }",
    "font[color=\"#ff0000\" i], font[color=\"red\" i] { color: #ff6666 !important; }",
    "/* === 帖子底部操作栏 (评分/点评)  & 列表项底部信息 === */",
    ".threadlist_foot { background: #1e1e1e !important; border-color: #333 !important; }",
    ".threadlist_foot a, .threadlist_foot i, .threadlist_foot em { color: #888888 !important; }",
    ".threadlist_foot li { border: 1px solid #555 !important; outline: none !important; box-shadow: none !important; }",
    ".threadlist_foot li.mr { border: none !important; }",
    ".threadlist_foot .dm-heart, .threadlist_foot .dm-chat-s, .dm-heart, .dm-chat-s, .dm-eye-fill, .dm-chat-s-fill { color: #888888 !important; }",
    "/* === 帖子列表项 - 顶部 (头像+用户名) === */",
    ".threadlist_top, .threadlist_top a, .threadlist_top .mimg, .threadlist_top .muser { background: #1e1e1e !important; }",
    ".threadlist_top .mmc { color: #bbbbbb !important; }",
    ".threadlist_top .mtime { color: #777777 !important; }",
    "/* === 帖子列表项 - 标题&摘要 === */",
    ".threadlist_tit, .threadlist_tit em, .threadlist_tit a { background: #1e1e1e !important; color: #dddddd !important; }",
    ".threadlist_mes, .threadlist_mes a { background: #1e1e1e !important; color: #999999 !important; }",
    "/* === 帖子间分隔 === */",
    ".discuz_x { background: #1e1e1e !important; border-color: #333 !important; }",
    "/* === 倒序/只看楼主 栏 === */",
    ".txtlist, .txtlist .mtit { background: #1a1a1a !important; color: #bbbbbb !important; border-color: #333 !important; }",
    ".txtlist .ytxt, .txtlist a { color: #aaaaaa !important; }",
    "/* === 帖子元信息行 === */",
    ".mtime, .mtime span, .mtime em, .mtime i { color: #888888 !important; }",
    ".y, .y span, .y em, .y i { color: #888888 !important; }",
    ".pstatus, .pstatus font { color: #888888 !important; }",
    "/* === 浮动菜单 (回到顶部) === */",
    ".float-menu-item { background: rgba(51, 51, 51, 0.85) !important; color: #bbbbbb !important; }",
    ".float-menu-item svg { fill: #bbbbbb !important; color: #bbbbbb !important; }",
    ".scrolltop { background: #333 !important; }",
    "#mask { background: rgba(0,0,0,0.7) !important; }",
    "/* === 通用文本覆盖 === */",
    "strong, b, .strong { color: #dddddd !important; }",
    "sup, sub { color: #aaaaaa !important; }",
    "em { color: #bbbbbb !important; }",
    ".display, .pi { background: #1e1e1e !important; }",
    "/* === 修复夜间模式头像被 DOM 层叠覆盖 === */",
    ".plc .avatar { z-index: 10 !important; background: transparent !important; }",
    ".plc .display, .plc .pi { background: transparent !important; }",
    "/* === 签到页 (hui 框架) === */",
    ".hui-header { background: #1a1a1a !important; }",
    ".hui-header h1 { color: #dddddd !important; }",
    ".hui-slide-menu { background: #1e1e1e !important; }",
    ".hui-slide-menu li { color: #bbbbbb !important; }",
    ".hui-wrap { background: #121212 !important; }",
    ".hui-common-title-line { border-color: #333 !important; }",
    ".hui-common-title-txt { color: #bbbbbb !important; }",
    ".hui-content { background: #1e1e1e !important; color: #bbbbbb !important; }",
    ".hui-media-list li { background: #1e1e1e !important; border-color: #333 !important; }",
    ".hui-media-content { background: #1e1e1e !important; }",
    ".hui-media-content p { color: #bbbbbb !important; }",
    ".hui-media-content a { color: #7eb8da !important; }",
    ".hui-list { background: #1e1e1e !important; }",
    ".hui-list-text { color: #bbbbbb !important; }",
    ".hui-center-title h2 { color: #dddddd !important; }",
    ".hui-button { background: #333 !important; color: #bbbbbb !important; }",
    ".hui-primary { background: #cc7755 !important; color: #fff !important; }",
    ".fl-table { background: #1e1e1e !important; }",
    ".fl-table th { background: #252525 !important; color: #bbbbbb !important; }",
    ".fl-table td { background: #1e1e1e !important; color: #bbbbbb !important; }",
    ".day { color: #bbbbbb !important; }",
    ".day.today { background: #cc7755 !important; color: #fff !important; }",
    ".lunar { color: #888888 !important; }",
    ".signbtn .btna { background: #cc7755 !important; color: #fff !important; }",
    "/* === 发帖时间/楼层号 === */",
    ".authi .mtit, .authi .mtime { color: #888888 !important; }",
    "/* === PhotoSwipe按钮 === */",
    ".pswp__button, .pswp__button:hover, .pswp__button:active { background: transparent !important; border-color: transparent !important; box-shadow: none !important; }"
)
