package org.shirakawatyu.yamibo.novel.util.theme

val LIGHT_MODE_CSS_RULES_MODERN_WHITE = listOf(
    "/* === Modern white theme, based on Discuz/Yamibo color variables === */",
    "body {",
    "--dz-BG-body: #F7F8FA !important;",
    "--dz-BG-color: #64748B !important;",
    "--dz-BG-0: #FFFFFF !important;",
    "--dz-BG-1: #64748B !important;",
    "--dz-BG-2: #E5484D !important;",
    "--dz-BG-3: #F59E0B !important;",
    "--dz-BG-4: #65A30D !important;",
    "--dz-BG-5: #EEF2F6 !important;",
    "--dz-BG-6: #CBD5E1 !important;",
    "--dz-BG-n: #DBEAFE !important;",
    "--dz-FC-color: #475569 !important;",
    "--dz-FC-fff: #FFFFFF !important;",
    "--dz-FC-333: #111827 !important;",
    "--dz-FC-666: #374151 !important;",
    "--dz-FC-777: #4B5563 !important;",
    "--dz-FC-888: #5B6472 !important;",
    "--dz-FC-999: #6B7280 !important;",
    "--dz-FC-aaa: #64748B !important;",
    "--dz-FC-bbb: #7B8794 !important;",
    "--dz-FC-ccc: #94A3B8 !important;",
    "--dz-FC-ddd: #CBD5E1 !important;",
    "--dz-FC-nnn: #3B82F6 !important;",
    "--dz-FC-light: #F59E0B !important;",
    "--dz-FC-a: #D04F35 !important;",
    "--dz-FC-v: #4D8A2A !important;",
    "--dz-FC-invalid: #E5484D !important;",
    "--dz-FC-tinvalid: #F4A6A6 !important;",
    "--dz-BOR-ed: #E2E8F0 !important;",
    "--dz-BOR-ccc: #CBD5E1 !important;",
    "--dz-BOR-invalid: #F4A6A6 !important;",
    "--yami-title-text: #FFFFFF !important;",
    "--yami-title-bg: #64748B !important;",
    "--yami-panel-bg: #FFFFFF !important;",
    "}",
    "html, body { background: #F7F8FA !important; color: #111827 !important; }",
    ".wp, #wp, .content, .main, .wrapper, .hui-wrap { background: #F7F8FA !important; }",
    ".header, .header_toplogo, .hui-header { background: #64748B !important; border-color: #64748B !important; color: #FFFFFF !important; }",
    ".header, .header h2, .header h2 a, .header a, .header i, .header_toplogo p, .hui-header h1, .hui-header a, .hui-header i { color: #FFFFFF !important; }",
    ".header .myss a { background: rgba(255, 255, 255, 0.16) !important; color: #F8FAFC !important; }",
    ".header .myss a i { color: #F8FAFC !important; }",
    ".header .myss a[href*=\"search.php?mod=forum\"] { background: #64748B !important; color: #FFFFFF !important; padding: 0 !important; }",
    ".header .myss a[href*=\"search.php?mod=forum\"] i { color: #FFFFFF !important; margin-right: 0 !important; }",
    "#nav-more-menu { background: #FFFFFF !important; border: 1px solid #E2E8F0 !important; box-shadow: 0 10px 28px rgba(15, 23, 42, 0.12) !important; }",
    "#nav-more-menu a:active { background: #EEF2F6 !important; }",
    ".nav-more-item, .nav-more-item-text, .nav-more-item svg { color: #111827 !important; fill: #111827 !important; }",
    ".sq_nav, .thread_nav, .sq_nav ul, .thread_nav ul, .z, .vertical_tab, .dhnav_box, #dhnav, #dhnav_li, .dhnavs_box, #dhnavs, .tabs { background: #FFFFFF !important; border-color: #E2E8F0 !important; }",
    ".sq_nav a, .thread_nav a, .z a, .vertical_tab a, .dhnav_box a, #dhnav a, #dhnavs .swiper-slide a, .tabs a { color: #4B5563 !important; }",
    ".sq_nav .a a, .thread_nav .a a, .sq_nav a.active, .thread_nav a.active, .z .a, .vertical_tab .a, .z a.active, .vertical_tab a.active, .dhnav_box .mon a, #dhnav .mon a, #dhnavs .swiper-slide.mon a, .tabs a.mon, .flex.mon a { color: #111827 !important; background: transparent !important; border-bottom-color: #64748B !important; }",
    ".forumdisplay-top { background: #FFFFFF !important; }",
    ".forumdisplay-top h2, .forumdisplay-top h2 a { color: #111827 !important; }",
    ".forumdisplay-top p, .forumdisplay-top p span { color: #64748B !important; }",
    ".forumlist, .forumlist > div, .forumlist .mlist1, .threadlist, .page, .discuz_x { background: #F7F8FA !important; }",
    ".forumlist .subforumshow, .subforumshow { background: #64748B !important; border-color: #64748B !important; color: #FFFFFF !important; }",
    ".subforumshow h2 a, .subforumshow a, .subforumshow i, .forumlist .subforumshow a, .forumlist .subforumshow i { color: #FFFFFF !important; }",
    ".forumlist .sub-forum, .mlist1, .mlist1 ul, .mlist1 li, .mlist1 li a, .mlist1 li span, .bm, .bm_c, .bm_h, .tl_bm, .tl_bm ul, .tl_bm li, .tl_bm li a, .threadlist li, .threadlist li a, .threadlist_top, .threadlist_top a, .threadlist_top .mimg, .threadlist_top .muser, .threadlist_tit, .threadlist_tit em, .threadlist_tit a, .threadlist_mes, .threadlist_mes a, .discuz_x, .view_tit, .view_tit h1, .view_tit a, .view_tit em, .plc, .plm, .plc div, .plm div, .hui-content, .hui-media-list li, .hui-media-content, .hui-list { background: #FFFFFF !important; }",
    ".mlist1 li, .tl_bm li, .threadlist li, .bm, .bm_c, .bm_h, .discuz_x, .hui-media-list li { border-color: #E2E8F0 !important; }",
    ".murl .mtit, .sub-forum .murl .mtit, .mlist1 .mtit, .bm_h, .bm_h h2, .bm_h a, .tl_bm a, .threadlist a, .threadlist_top .mmc, .threadlist_tit, .threadlist_tit em, .threadlist_tit a, .view_tit, .view_tit h1, .view_tit a, .view_tit em, .message, .postmessage, .t_f, .t_msgfont, .message div, .t_f div, .hui-common-title-txt, .hui-media-content p, .hui-list-text, .hui-center-title h2 { color: #111827 !important; }",
    ".mlist1 .mtxt, .threadlist_mes, .threadlist_mes a, .authi, .authi em, .authi a, .authi span, .xg1, .xg1 a, .txtlist .ytxt, .txtlist a, .hui-media-content a { color: #4B5563 !important; }",
    ".num, .views, .replies, .ts, .time, .threadlist_top .mtime, .mtime, .mtime span, .mtime em, .mtime i, .y, .y span, .y em, .y i, .pstatus, .pstatus font, .xg2, .xg2 a { color: #64748B !important; }",
    ".lock, .closed, .icn, .attach, .tattl { color: #64748B !important; }",
    ".fico-launch, .dm-star, .fico-reply, .fico-favorite, .fico-share, .fico, .dm-heart, .dm-chat-s, .dm-eye-fill, .dm-chat-s-fill { color: #64748B !important; }",
    ".psth, .plc .psth { background: #EEF2F6 !important; color: #374151 !important; border-color: #E2E8F0 !important; }",
    ".psth .icon_ring, .plc .psth .icon_ring { color: #64748B !important; }",
    ".showcollapse_box { background: #FFFFFF !important; border-color: #E2E8F0 !important; }",
    ".showcollapse_title { background: #EEF2F6 !important; color: #111827 !important; border-color: #E2E8F0 !important; }",
    ".showcollapse_content { background: #FFFFFF !important; color: #111827 !important; }",
    ".showcollapse_content a { color: #2563EB !important; }",
    ".showcollapse_gather { color: #4B5563 !important; }",
    ".message a, .postmessage a, .t_f a, .t_msgfont a, a.link, .xi2 { color: #2563EB !important; }",
    ".pls, .pls div, .pls a, .pgs, .pgs a, .pg, .pg a, .page a, .txtlist, .txtlist .mtit, blockquote, .quote, .blockcode, .notice, .tip, .alert, .warning, .tips, .poll, .reward, .rwdbst, .debate_box, .activity, .trade_box { background: #EEF2F6 !important; color: #374151 !important; border-color: #E2E8F0 !important; }",
    ".pls em, .pls span { color: #4B5563 !important; }",
    ".authi .mtit { color: #64748B !important; }",
    ".threadlist_foot { background: #FFFFFF !important; border-color: #E2E8F0 !important; color: #64748B !important; }",
    ".threadlist_foot a, .threadlist_foot i, .threadlist_foot em { color: #4B5563 !important; }",
    ".threadlist_foot li { border: 1px solid #E2E8F0 !important; outline: none !important; box-shadow: none !important; color: #64748B !important; }",
    ".threadlist_foot li.mr { border: none !important; }",
    ".pgs .pg strong, .pg strong, .page strong, .pn, .btn_pn, .btn_pn_blue, .button2, .pns, .button, .hui-primary, .signbtn .btna, .scrolltop, .mbtn { background: #64748B !important; color: #FFFFFF !important; border-color: #64748B !important; }",
    ".foot, .foot_reply, .f_c, #f_c { background: #FFFFFF !important; border-color: #E2E8F0 !important; color: #4B5563 !important; }",
    ".foot a, .foot_reply a, .f_c a, .foot a span.foot-txt { color: #4B5563 !important; }",
    ".footer, #footer { background: #64748B !important; color: #F8FAFC !important; border-color: #64748B !important; }",
    ".footer a, #footer a { color: #F8FAFC !important; }",
    ".footer-nv, .footer-nv a, .footer-copy, .footer-copy a { background: #64748B !important; color: #F8FAFC !important; }",
    ".footer .mon { color: #FFFFFF !important; }",
    ".foot a.mon span.foot-txt, .viewt-reply, .viewt-reply a { color: #111827 !important; }",
    ".foot_reply .viewt-reply { background: #EEF2F6 !important; color: #4B5563 !important; }",
    ".my, .my a, .mz, .mz a, .my i, .my span, .mz i, .mz span { color: #FFFFFF !important; }",
    ".myinfo_list_ico, .myinfo_list_ico ul, .myinfo_list_ico li, .myinfo, .myinfo_menu, .profile_section, .profile_section a { background: #FFFFFF !important; border-color: #E2E8F0 !important; }",
    ".myinfo_list_ico li a, .setbox li.tit, .dzcell-item, .dzcell-group, .showcollapse_title { background: #EEF2F6 !important; color: #111827 !important; }",
    ".myinfo_list_ico li i { color: #FFFFFF !important; }",
    ".avatar_bg h2.name, h2.name { color: #FFFFFF !important; }",
    ".avatar_bg .name, .myinfo a, .myinfo_menu a, .myinfo_list b { color: #111827 !important; }",
    ".myinfo_list li span, .mtag, .profile_tag { color: #4B5563 !important; }",
    ".myinfo_list, .myinfo_list li { border-color: #E2E8F0 !important; }",
    ".avatar img, .avatar, .my_avatar img { border-color: #E2E8F0 !important; }",
    ".plc .avatar { z-index: 10 !important; background: transparent !important; }",
    ".plc .avatar a, .plc .avatar img { background: transparent !important; }",
    ".display, .pi { background: #FFFFFF !important; }",
    ".plc .display, .plc .pi { background: transparent !important; }",
    "strong, b, .strong { color: #111827 !important; }",
    "sup, sub, em { color: #4B5563 !important; }",
    "input, select, textarea, #postform, #fastpostform, .area textarea, table, tbody, td, th, .t_table, .t_table td, .t_table th { background: #FFFFFF !important; color: #111827 !important; border-color: #CBD5E1 !important; }",
    "hr, .line, .partition, .pipe { border-color: #E2E8F0 !important; color: #94A3B8 !important; }",
    ".message *[style*=\"background\" i] { background-color: transparent !important; }",
    "font[color] { color: #111827 !important; }",
    "font[color=\"#ff0000\" i], font[color=\"red\" i], .xi1, .rq { color: #E5484D !important; }",
    ".float-menu-item { background: rgba(255,255,255,0.94) !important; color: #111827 !important; border: 1px solid #E2E8F0 !important; box-shadow: 0 8px 20px rgba(15, 23, 42, 0.12) !important; }",
    ".float-menu-item svg { color: #111827 !important; fill: #111827 !important; }",
    "#mask { background: rgba(15, 23, 42, 0.32) !important; }",
    ".pswp__button, .pswp__button:hover, .pswp__button:active { background: transparent !important; border-color: transparent !important; box-shadow: none !important; }",
    ".dialog, .ui-dialog, .bootstrap-dialog, .pop, .p_pop, .p_pop div { background: #FFFFFF !important; color: #111827 !important; }",
    ".dialog a, .ui-dialog a, .p_pop a { color: #2563EB !important; }",
    "/* === Modern white contrast pass: keep original Discuz hierarchy but make small text readable on white === */",
    "a.grey:link, a.grey:visited, a.grey:hover, .grey, .f_9, .f_9 a, .fc-s { color: #6B7280 !important; }",
    ".forumlist .sub-forum li .mtxt, .imglist li .mtxt, .annlist li h3, .annlist li h3 span, .search-hot h2, .setbox li, .dzcell-item .dzcell-value, .home_credit_log li .txt, .home_credit_log li .txt a, .home_credit_log li .mtime, .album_depict, .album_name span, .medallist .mg_tit span, .medal_tip_box ul li span { color: #4B5563 !important; }",
    ".stat, .stat li, .empty-box h4, .threadlist_top .muser .mtime, .imglist li .mtit .mtime, .pipe, .threadlist_mes .mtime { color: #64748B !important; }",
    ".stat li em, .album_name .albumname, .last_medal li .name, .forumdisplay-top h2, .hotbox-toutiao a span { color: #111827 !important; }",
    ".forumlist .sub-forum li .mnum, .mlist1 .mnum, .threadlist .mnum { color: #D92D20 !important; }",
    ".forumdisplay-top p span, .xi1, .rq, .onerror { color: #D92D20 !important; }",
    ".btn_pn_grey, .flw_loadmore.pn { background: #FFFFFF !important; color: #475569 !important; border: 1px solid #E2E8F0 !important; }",
    ".hotbox-toutiao a, .listbox li span.mbk, .listbox li span.mybk, .imglist li .mbody, .album_inof p { color: #4B5563 !important; }",
    ".listbox li i, .listbox li span.mx, .imglist li .mtxt i { color: #94A3B8 !important; }",
    ".foot a.mon span.foot-ico em, .foot a.mon span.foot-txt { color: #475569 !important; }",
    ".foot_reply .viewt-reply, .foot_reply .viewt-reply i { color: #4B5563 !important; }",
    ".footer-copy, .footer-copy a, .footer-nv, .footer-nv a { color: #F8FAFC !important; }",
    ".micon { color: #FFFFFF !important; }",
    "#a_newthread { background: #64748B !important; color: #FFFFFF !important; border-color: #64748B !important; }",
    "#a_newthread i { color: #FFFFFF !important; }"
)
