package org.shirakawatyu.yamibo.novel.util.theme

val LIGHT_MODE_CSS_RULES_COBALT_FORUM = listOf(
    "/* === CSS 变量覆盖 (论坛蓝日间版 · 经典 #2B7ACD 蓝) === */",
    "body {",
    "--dz-BG-body: #EDF1F6 !important;",
    "--dz-BG-0: #FFFFFF !important;",
    "--dz-BG-5: #DDE7F1 !important;",
    "--dz-BG-6: #BAC9D9 !important;",
    "--dz-FC-fff: #1A2733 !important;",
    "--dz-FC-333: #1A2733 !important;",
    "--dz-FC-666: #5B6A7A !important;",
    "--dz-FC-999: #7C8B9A !important;",
    "--dz-FC-ccc: #B3C0CC !important;",
    "--dz-FC-aaa: #9DACBA !important;",
    "--dz-BOR-ed: #CFDAE5 !important;",
    "--dz-FC-color: #2B7ACD !important;",
    "}",
    "html, body { background: #EDF1F6 !important; }",
    ".wp, #wp, .content, .main, .wrapper { background: #EDF1F6 !important; }",
    ".header { background: #1F5A8F !important; border-color: #1F5A8F !important; }",
    ".header, .header h2, .header h2 a, .header a { color: #FFFFFF !important; }",
    ".header i { color: #FFFFFF !important; }",
    ".header_toplogo { background: #1F5A8F !important; }",
    ".header_toplogo p { color: #FFFFFF !important; }",
    ".header .myss a { background: #1F5A8F !important; color: #D0D8E8 !important; }",
    ".header .myss a i { color: #D0D8E8 !important; }",
    "#nav-more-menu { background: #FFFFFF !important; }",
    ".nav-more-item { color: #1A2733 !important; }",
    ".nav-more-item-text { color: #1A2733 !important; }",
    ".nav-more-item svg { fill: #1A2733 !important; color: #1A2733 !important; }",
    ".sq_nav, .thread_nav, .sq_nav ul, .thread_nav ul { background: #DDE7F1 !important; }",
    ".sq_nav a, .thread_nav a { color: #5B6A7A !important; }",
    ".sq_nav .a a, .thread_nav .a a, .sq_nav a.active, .thread_nav a.active { color: #0E1822 !important; background: #CFDDEC !important; }",
    ".z, .vertical_tab { background: #DDE7F1 !important; }",
    ".z a, .vertical_tab a { color: #5B6A7A !important; }",
    ".z .a, .vertical_tab .a, .z a.active, .vertical_tab a.active { color: #0E1822 !important; background: #CFDDEC !important; }",
    ".plc .z, .plc .flex-2, .plc .xg1, .plc .xw1 { background: #FFFFFF !important; }",
    ".forumdisplay-top { background: #2D6BA8 !important; }",
    ".forumdisplay-top h2, .forumdisplay-top h2 a { color: #FFFFFF !important; }",
    ".forumdisplay-top p, .forumdisplay-top p span { color: #D1E2F2 !important; }",
    ".forumdisplay-top a { color: #FFFFFF !important; }",
    ".dhnav_box, #dhnav, #dhnav_li { background: #DDE7F1 !important; }",
    ".dhnav_box a, #dhnav a { color: #5B6A7A !important; }",
    ".dhnav_box .mon a, #dhnav .mon a { color: #0E1822 !important; }",
    ".tabs a.mon, .dhnv a.mon, #dhnav_li li.mon { border-bottom-color: #2B7ACD !important; color: #1F5A8F !important; }",
    ".dhnavs_box, #dhnavs { background: #DDE7F1 !important; }",
    "#dhnavs .swiper-slide a { color: #5B6A7A !important; }",
    "#dhnavs .swiper-slide.mon a { color: #0E1822 !important; }",
    ".forumlist, .forumlist > div, .forumlist .mlist1 { background: #EDF1F6 !important; }",
    ".forumlist .subforumshow { background: #2D6BA8 !important; }",
    ".subforumshow { background: #2D6BA8 !important; border-color: #2D6BA8 !important; }",
    ".subforumshow h2 a { color: #FFFFFF !important; }",
    ".subforumshow i { color: #D1E2F2 !important; }",
    ".subforumshow { color: #D1E2F2 !important; }",
    ".subforumshow a { color: #FFFFFF !important; }",
    ".murl .mtit, .sub-forum .murl .mtit { color: #1A2733 !important; }",
    ".mlist1, .mlist1 ul, .mlist1 li, .mlist1 li a, .mlist1 li span { background: #FFFFFF !important; }",
    ".mlist1 li { border-color: #CFDAE5 !important; }",
    ".mlist1 .mtit { color: #1A2733 !important; }",
    ".mlist1 .mtxt { color: #7C8B9A !important; }",
    ".mlist1 .mnum { color: #9DACBA !important; }",
    ".bm, .bm_c, .bm_h { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".bm_h, .bm_h h2, .bm_h a { color: #1A2733 !important; }",
    ".tl_bm, .tl_bm ul, .tl_bm li, .tl_bm li a { background: #FFFFFF !important; }",
    ".threadlist { background: #DDE7F1 !important; }",
    ".threadlist li, .threadlist li a { background: #FFFFFF !important; }",
    ".tl_bm li, .threadlist li { border-color: #CFDAE5 !important; }",
    ".tl_bm a, .threadlist a { color: #1A2733 !important; }",
    ".view_tit, .view_tit h1, .view_tit a, .view_tit em { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".pls, .pls div, .pls a { background: #DDE7F1 !important; }",
    ".pls, .pls a, .pls em, .pls span { color: #1A2733 !important; }",
    ".plc, .plm, .plc div, .plm div { background: #FFFFFF !important; }",
    ".authi, .authi em, .authi a, .authi span { color: #5B6A7A !important; }",
    ".message, .postmessage, .t_f, .t_msgfont, .message div, .t_f div { color: #1A2733 !important; }",
    ".message a, .postmessage a, .t_f a, .t_msgfont a { color: #1F5A8F !important; }",
    ".pgs, .pgs a, .pg, .pg a { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    ".page { background: #EDF1F6 !important; }",
    ".page a { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    ".pgs .pg strong, .pg strong, .page strong { background: #2B7ACD !important; color: #FFFFFF !important; }",
    ".xi1 { color: #1A2733 !important; }",
    ".xi2 { color: #1A2733 !important; }",
    ".xg1, .xg1 a { color: #5B6A7A !important; }",
    ".xg2, .xg2 a { color: #7C8B9A !important; }",
    ".num, .views, .replies { color: #7C8B9A !important; }",
    ".ts, .time { color: #9DACBA !important; }",
    ".pipe { color: #B3C0CC !important; }",
    ".lock, .closed, .icn, .attach, .tattl { color: #7C8B9A !important; }",
    ".dialog, .ui-dialog, .bootstrap-dialog, .pop, .p_pop, .p_pop div { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".dialog a, .ui-dialog a, .p_pop a { color: #1A2733 !important; }",
    ".foot_reply, .f_c, .foot, #f_c { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".foot_reply a, .f_c a, .foot a { color: #1A2733 !important; }",
    ".viewt-reply, .viewt-reply a { background: #CFDDEC !important; color: #0E1822 !important; }",
    ".fico-launch, .dm-star, .fico-reply, .fico-favorite, .fico-share, .fico { color: #1A2733 !important; }",
    ".my, .my a { color: #FFFFFF !important; }",
    ".my i, .my span { color: #FFFFFF !important; }",
    ".mz, .mz a, .mz i, .mz span { color: #FFFFFF !important; }",
    ".myinfo_list_ico, .myinfo_list_ico ul { background: #FFFFFF !important; }",
    ".myinfo_list_ico li { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".myinfo_list_ico li a { background: #DDE7F1 !important; color: #1A2733 !important; }",
    ".myinfo_list_ico li i { color: #FFFFFF !important; }",
    ".avatar_bg .name { color: #FFFFFF !important; }",
    ".myinfo, .myinfo_menu, .profile_section, .profile_section a { background: #FFFFFF !important; }",
    ".myinfo a, .myinfo_menu a { color: #1A2733 !important; }",
    ".myinfo_list, .myinfo_list li { border-color: #CFDAE5 !important; }",
    ".myinfo_list li span { color: #5B6A7A !important; }",
    ".myinfo_list b { color: #1A2733 !important; }",
    ".mtag, .profile_tag { color: #7C8B9A !important; }",
    "table, tbody, td, th, .t_table, .t_table td, .t_table th { background: #FFFFFF !important; color: #1A2733 !important; border-color: #CFDAE5 !important; }",
    ".footer, #footer { background: #DDE7F1 !important; color: #7C8B9A !important; border-color: #CFDAE5 !important; }",
    ".footer a, #footer a { color: #7C8B9A !important; }",
    ".footer-nv, .footer-nv a, .footer-copy, .footer-copy a { background: #DDE7F1 !important; color: #7C8B9A !important; }",
    ".footer .mon { color: #7C8B9A !important; }",
    "input, select, textarea { background: #FFFFFF !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    "blockquote, .quote, .blockcode { background: #DDE7F1 !important; border-color: #BAC9D9 !important; color: #5B6A7A !important; }",
    "hr, .line, .partition { border-color: #CFDAE5 !important; }",
    ".notice, .tip, .alert, .warning, .tips { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    ".avatar img, .avatar, .my_avatar img { border-color: #CFDAE5 !important; }",
    ".btn, .button, button, .pn, .pnc { background: #CFDDEC !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    "#postform, #fastpostform, .area textarea { background: #FFFFFF !important; color: #1A2733 !important; border-color: #BAC9D9 !important; }",
    ".psth { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #CFDAE5 !important; }",
    ".psth .icon_ring { color: #5B6A7A !important; }",
    ".showcollapse_box { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".showcollapse_title { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #CFDAE5 !important; }",
    ".showcollapse_content { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".showcollapse_content a { color: #1F5A8F !important; }",
    ".showcollapse_gather { color: #7C8B9A !important; }",
    ".message *[style*=\"background\" i] { background-color: transparent !important; }",
    "font[color] { color: #1A2733 !important; }",
    "font[color=\"#ff0000\" i], font[color=\"red\" i] { color: #C04A3A !important; }",
    ".threadlist_foot { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".threadlist_foot a, .threadlist_foot i, .threadlist_foot em { color: #7C8B9A !important; }",
    ".threadlist_foot li { border: 1px solid #BAC9D9 !important; outline: none !important; box-shadow: none !important; }",
    ".threadlist_foot li.mr { border: none !important; }",
    ".threadlist_foot .dm-heart, .threadlist_foot .dm-chat-s, .dm-heart, .dm-chat-s, .dm-eye-fill, .dm-chat-s-fill { color: #888888 !important; }",
    ".threadlist_top, .threadlist_top a, .threadlist_top .mimg, .threadlist_top .muser { background: #FFFFFF !important; }",
    ".threadlist_top .mmc { color: #1A2733 !important; }",
    ".threadlist_top .mtime { color: #9DACBA !important; }",
    ".threadlist_tit, .threadlist_tit em, .threadlist_tit a { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".threadlist_mes, .threadlist_mes a { background: #FFFFFF !important; color: #7C8B9A !important; }",
    ".discuz_x { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".txtlist, .txtlist .mtit { background: #DDE7F1 !important; color: #1A2733 !important; border-color: #CFDAE5 !important; }",
    ".txtlist .ytxt, .txtlist a { color: #5B6A7A !important; }",
    ".mtime, .mtime span, .mtime em, .mtime i { color: #7C8B9A !important; }",
    ".y, .y span, .y em, .y i { color: #7C8B9A !important; }",
    ".pstatus, .pstatus font { color: #7C8B9A !important; }",
    ".float-menu-item { background: rgba(255, 255, 255, 0.92) !important; color: #1A2733 !important; border: 1px solid #CFDAE5 !important; }",
    ".float-menu-item svg { fill: #1A2733 !important; color: #1A2733 !important; }",
    ".scrolltop { background: #2B7ACD !important; color: #FFFFFF !important; }",
    ".scrolltop i, .scrolltop svg { color: #FFFFFF !important; fill: #FFFFFF !important; }",
    "#mask { background: rgba(0,0,0,0.32) !important; }",
    "strong, b, .strong { color: #1A2733 !important; }",
    "sup, sub { color: #5B6A7A !important; }",
    "em { color: #1A2733 !important; }",
    ".display, .pi { background: #FFFFFF !important; }",
    ".plc .avatar { z-index: 10 !important; background: transparent !important; }",
    ".plc .display, .plc .pi { background: transparent !important; }",
    ".hui-header { background: #1F5A8F !important; }",
    ".hui-header h1 { color: #FFFFFF !important; }",
    ".hui-header a, .hui-header i { color: #FFFFFF !important; }",
    ".hui-slide-menu { background: #FFFFFF !important; }",
    ".hui-slide-menu li { color: #1A2733 !important; }",
    ".hui-wrap { background: #EDF1F6 !important; }",
    ".hui-common-title-line { border-color: #CFDAE5 !important; }",
    ".hui-common-title-txt { color: #1A2733 !important; }",
    ".hui-content { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".hui-media-list li { background: #FFFFFF !important; border-color: #CFDAE5 !important; }",
    ".hui-media-content { background: #FFFFFF !important; }",
    ".hui-media-content p { color: #1A2733 !important; }",
    ".hui-media-content a { color: #1F5A8F !important; }",
    ".hui-list { background: #FFFFFF !important; }",
    ".hui-list-text { color: #1A2733 !important; }",
    ".hui-center-title h2 { color: #1A2733 !important; }",
    ".hui-button { background: #CFDDEC !important; color: #1A2733 !important; }",
    ".hui-primary { background: #2B7ACD !important; color: #FFFFFF !important; }",
    ".fl-table { background: #FFFFFF !important; }",
    ".fl-table th { background: #DDE7F1 !important; color: #1A2733 !important; }",
    ".fl-table td { background: #FFFFFF !important; color: #1A2733 !important; }",
    ".day { color: #1A2733 !important; }",
    ".day.today { background: #2B7ACD !important; color: #FFFFFF !important; }",
    ".lunar { color: #7C8B9A !important; }",
    ".signbtn .btna { background: #2B7ACD !important; color: #FFFFFF !important; }",
    ".authi .mtit, .authi .mtime { color: #7C8B9A !important; }",
    ".pswp__button, .pswp__button:hover, .pswp__button:active { background: transparent !important; border-color: transparent !important; box-shadow: none !important; }"
)
